/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author chuch
 */
public class MainMenu extends javax.swing.JFrame
{

    /**
     * Creates new form MainMenu
     */
    public MainMenu()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pnlMenu = new javax.swing.JPanel();
        lblHome1 = new javax.swing.JLabel();
        lblHome2 = new javax.swing.JLabel();
        btnBST = new javax.swing.JButton();
        btnArray = new javax.swing.JButton();
        lblFileName = new javax.swing.JLabel();
        txtFileName = new javax.swing.JTextField();
        lblIntructions = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        btnChooseFile = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(null);
        setPreferredSize(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHome1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblHome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHome1.setText("Knowledge Base and Select The Data Structure You Would Like Below");
        lblHome1.setToolTipText("");
        pnlMenu.add(lblHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 780, 50));

        lblHome2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblHome2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHome2.setText("Welcome, Please Choose The File With The ");
        lblHome2.setToolTipText("");
        pnlMenu.add(lblHome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 780, 50));

        btnBST.setText("Binary Search Tree Data Structure");
        btnBST.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBSTActionPerformed(evt);
            }
        });
        pnlMenu.add(btnBST, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 350, 90));

        btnArray.setText("Array Data Structure");
        btnArray.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnArrayActionPerformed(evt);
            }
        });
        pnlMenu.add(btnArray, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 350, 90));

        lblFileName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFileName.setText("File Name:");
        pnlMenu.add(lblFileName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 70, 20));

        txtFileName.setEditable(false);
        pnlMenu.add(txtFileName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 210, -1));

        lblIntructions.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblIntructions.setForeground(new java.awt.Color(255, 0, 0));
        lblIntructions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIntructions.setText("Please Press The Choose File Button To Select Your File");
        pnlMenu.add(lblIntructions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 800, 20));

        lblError.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 0));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlMenu.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 800, 20));

        btnChooseFile.setText("Choose File");
        btnChooseFile.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnChooseFileActionPerformed(evt);
            }
        });
        pnlMenu.add(btnChooseFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/lib/Background image.jpg"))); // NOI18N
        lblBackground.setName(""); // NOI18N
        pnlMenu.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 510));

        getContentPane().add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArrayActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnArrayActionPerformed
    {//GEN-HEADEREND:event_btnArrayActionPerformed
        // TODO add your handling code here:
        lblError.setText("");
        if (txtFileName.getText().isBlank())
        {
            lblError.setText("Please Enter a text file");
        }
        else
        {
           File f = new File(txtFileName.getText());
           if(f.exists())
           {
                new MenuArr(txtFileName.getText()).setVisible(true);
                dispose();
           }
           else
           {
               lblError.setText("File not found. Please reenter file name");
           }
        }
    }//GEN-LAST:event_btnArrayActionPerformed

    private void btnBSTActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBSTActionPerformed
    {//GEN-HEADEREND:event_btnBSTActionPerformed
        // TODO add your handling code here:
        lblError.setText("");
        if (txtFileName.getText().isBlank())
        {
            lblError.setText("Please Enter a text file");
        }
        else
        {
           File f = new File(txtFileName.getText());
           if(f.exists())
           {
                new MenuBST(txtFileName.getText()).setVisible(true);
                dispose();
           }
           else
           {
               lblError.setText("File not found. Please reenter file name");
           }
        }
    }//GEN-LAST:event_btnBSTActionPerformed

    private void btnChooseFileActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnChooseFileActionPerformed
    {//GEN-HEADEREND:event_btnChooseFileActionPerformed
        lblError.setText("");
        String path = "";
        JFileChooser j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int x = j.showSaveDialog(this);
        
        if(x==JFileChooser.APPROVE_OPTION)
        {
            
            path = j.getSelectedFile().getPath();
            txtFileName.setText(path);
        }
        else
        {
            lblError.setText("Please Enter a text file");
        }
    }//GEN-LAST:event_btnChooseFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArray;
    private javax.swing.JButton btnBST;
    private javax.swing.JButton btnChooseFile;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblFileName;
    private javax.swing.JLabel lblHome1;
    private javax.swing.JLabel lblHome2;
    private javax.swing.JLabel lblIntructions;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JTextField txtFileName;
    // End of variables declaration//GEN-END:variables
}
